# apiVersion: apps/v1
# kind: Deployment
# metadata: # metadata about the Deployment
#   name: jobfinders-deployment-ann
# spec: # defines the desired state of the Deployment.
#   replicas: 2 # specifies how many identical replicas (pods) of the application should be maintained, in this case, 2, which means Kubernetes will ensure that two pods running the specified container are always available
#   selector:
#     matchLabels:
#       app: jf-docker-img
#   template: # defines the pod template used by the Deployment. It specifies the pod's metadata and the container(s) to run.
#     metadata: #specifies the pod's metadata
#       labels:
#         app: jf-docker-img
#     spec: # specifies the container(s) to run
#       containers:
#       - name: jf-container
#       image: anrasjar/jf-docker-img:latest
#       ports:
#       - containerPort: 5055 # specifies the port that the application listens on 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobfinders-deployment-ann
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jf-docker-img
  template:
    metadata:
      labels:
        app: jf-docker-img
    spec:
      containers:
      - name: jf-container
        image: anrasjar/jf-docker-img:latest
        ports:
        - containerPort: 5055
